//! Inventory identities and Beta stack rules. Definitions do not imply that
//! an item's use, crafting recipe, or rendering has been implemented.
use crate::world::block::block::BlockId;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ItemData {
    None,
    /// Highest supported subtype value (inclusive).
    Subtype(u16),
    /// Beta `maxDamage`. Stored data is uses so far; the item breaks when uses
    /// exceed this value.
    Durability(u16),
    Map,
}

impl ItemData {
    pub fn accepts(self, value: u16) -> bool {
        match self {
            Self::None => value == 0,
            Self::Subtype(max) | Self::Durability(max) => value <= max,
            Self::Map => true,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ItemDefinition {
    pub id: ItemId,
    pub name: &'static str,
    pub max_stack_size: u8,
    pub data: ItemData,
    /// Present for direct block items, not special items such as doors/buckets.
    pub block: Option<BlockId>,
}

impl ItemDefinition {
    /// Beta crafting remainder, for example an empty bucket left by milk.
    pub const fn container_item(self) -> Option<ItemId> {
        match self.id {
            ItemId::MilkBucket => Some(ItemId::Bucket),
            _ => None,
        }
    }
}

/// Block items share their block's Beta id. Standalone items start at 256.
///
/// The persisted id is [`ItemId::as_u16`], not a `#[repr]` discriminant:
/// [`ItemId::Block`] carries the catalog id in its payload. Resolve raw ids
/// with [`ItemId::from_u16`] before using them.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ItemId {
    Block(BlockId),
    IronShovel,
    IronPickaxe,
    IronAxe,
    FlintAndSteel,
    Apple,
    Bow,
    Arrow,
    Coal,
    Diamond,
    IronIngot,
    GoldIngot,
    IronSword,
    WoodenSword,
    WoodenShovel,
    WoodenPickaxe,
    WoodenAxe,
    StoneSword,
    StoneShovel,
    StonePickaxe,
    StoneAxe,
    DiamondSword,
    DiamondShovel,
    DiamondPickaxe,
    DiamondAxe,
    Stick,
    Bowl,
    MushroomStew,
    GoldSword,
    GoldShovel,
    GoldPickaxe,
    GoldAxe,
    String,
    Feather,
    Gunpowder,
    WoodenHoe,
    StoneHoe,
    IronHoe,
    DiamondHoe,
    GoldHoe,
    Seeds,
    Wheat,
    Bread,
    LeatherHelmet,
    LeatherChestplate,
    LeatherLeggings,
    LeatherBoots,
    ChainmailHelmet,
    ChainmailChestplate,
    ChainmailLeggings,
    ChainmailBoots,
    IronHelmet,
    IronChestplate,
    IronLeggings,
    IronBoots,
    DiamondHelmet,
    DiamondChestplate,
    DiamondLeggings,
    DiamondBoots,
    GoldHelmet,
    GoldChestplate,
    GoldLeggings,
    GoldBoots,
    Flint,
    RawPorkchop,
    CookedPorkchop,
    Painting,
    GoldenApple,
    Sign,
    WoodenDoor,
    Bucket,
    WaterBucket,
    LavaBucket,
    Minecart,
    Saddle,
    IronDoor,
    Redstone,
    Snowball,
    Boat,
    Leather,
    MilkBucket,
    Brick,
    ClayBall,
    SugarCane,
    Paper,
    Book,
    Slimeball,
    ChestMinecart,
    FurnaceMinecart,
    Egg,
    Compass,
    FishingRod,
    Clock,
    GlowstoneDust,
    RawFish,
    CookedFish,
    Dye,
    Bone,
    Sugar,
    Cake,
    Bed,
    Repeater,
    Cookie,
    Map,
    Shears,
    Record13,
    RecordCat,
}

const fn standalone(
    id: ItemId,
    name: &'static str,
    max_stack_size: u8,
    data: ItemData,
) -> ItemDefinition {
    ItemDefinition {
        id,
        name,
        max_stack_size,
        data,
        block: None,
    }
}

impl ItemId {
    pub const fn from_block(block: BlockId) -> Option<Self> {
        let raw = block.as_u8();
        if raw == 0 || raw > 96 {
            None
        } else {
            Some(Self::Block(block))
        }
    }

    pub const fn as_u16(self) -> u16 {
        match self {
            Self::Block(block) => block.as_u8() as u16,
            Self::IronShovel => 256,
            Self::IronPickaxe => 257,
            Self::IronAxe => 258,
            Self::FlintAndSteel => 259,
            Self::Apple => 260,
            Self::Bow => 261,
            Self::Arrow => 262,
            Self::Coal => 263,
            Self::Diamond => 264,
            Self::IronIngot => 265,
            Self::GoldIngot => 266,
            Self::IronSword => 267,
            Self::WoodenSword => 268,
            Self::WoodenShovel => 269,
            Self::WoodenPickaxe => 270,
            Self::WoodenAxe => 271,
            Self::StoneSword => 272,
            Self::StoneShovel => 273,
            Self::StonePickaxe => 274,
            Self::StoneAxe => 275,
            Self::DiamondSword => 276,
            Self::DiamondShovel => 277,
            Self::DiamondPickaxe => 278,
            Self::DiamondAxe => 279,
            Self::Stick => 280,
            Self::Bowl => 281,
            Self::MushroomStew => 282,
            Self::GoldSword => 283,
            Self::GoldShovel => 284,
            Self::GoldPickaxe => 285,
            Self::GoldAxe => 286,
            Self::String => 287,
            Self::Feather => 288,
            Self::Gunpowder => 289,
            Self::WoodenHoe => 290,
            Self::StoneHoe => 291,
            Self::IronHoe => 292,
            Self::DiamondHoe => 293,
            Self::GoldHoe => 294,
            Self::Seeds => 295,
            Self::Wheat => 296,
            Self::Bread => 297,
            Self::LeatherHelmet => 298,
            Self::LeatherChestplate => 299,
            Self::LeatherLeggings => 300,
            Self::LeatherBoots => 301,
            Self::ChainmailHelmet => 302,
            Self::ChainmailChestplate => 303,
            Self::ChainmailLeggings => 304,
            Self::ChainmailBoots => 305,
            Self::IronHelmet => 306,
            Self::IronChestplate => 307,
            Self::IronLeggings => 308,
            Self::IronBoots => 309,
            Self::DiamondHelmet => 310,
            Self::DiamondChestplate => 311,
            Self::DiamondLeggings => 312,
            Self::DiamondBoots => 313,
            Self::GoldHelmet => 314,
            Self::GoldChestplate => 315,
            Self::GoldLeggings => 316,
            Self::GoldBoots => 317,
            Self::Flint => 318,
            Self::RawPorkchop => 319,
            Self::CookedPorkchop => 320,
            Self::Painting => 321,
            Self::GoldenApple => 322,
            Self::Sign => 323,
            Self::WoodenDoor => 324,
            Self::Bucket => 325,
            Self::WaterBucket => 326,
            Self::LavaBucket => 327,
            Self::Minecart => 328,
            Self::Saddle => 329,
            Self::IronDoor => 330,
            Self::Redstone => 331,
            Self::Snowball => 332,
            Self::Boat => 333,
            Self::Leather => 334,
            Self::MilkBucket => 335,
            Self::Brick => 336,
            Self::ClayBall => 337,
            Self::SugarCane => 338,
            Self::Paper => 339,
            Self::Book => 340,
            Self::Slimeball => 341,
            Self::ChestMinecart => 342,
            Self::FurnaceMinecart => 343,
            Self::Egg => 344,
            Self::Compass => 345,
            Self::FishingRod => 346,
            Self::Clock => 347,
            Self::GlowstoneDust => 348,
            Self::RawFish => 349,
            Self::CookedFish => 350,
            Self::Dye => 351,
            Self::Bone => 352,
            Self::Sugar => 353,
            Self::Cake => 354,
            Self::Bed => 355,
            Self::Repeater => 356,
            Self::Cookie => 357,
            Self::Map => 358,
            Self::Shears => 359,
            Self::Record13 => 2256,
            Self::RecordCat => 2257,
        }
    }

    pub const fn from_u16(value: u16) -> Option<Self> {
        if value <= 96 {
            return match BlockId::from_u8(value as u8) {
                Some(block) => Self::from_block(block),
                None => None,
            };
        }
        Some(match value {
            256 => Self::IronShovel,
            257 => Self::IronPickaxe,
            258 => Self::IronAxe,
            259 => Self::FlintAndSteel,
            260 => Self::Apple,
            261 => Self::Bow,
            262 => Self::Arrow,
            263 => Self::Coal,
            264 => Self::Diamond,
            265 => Self::IronIngot,
            266 => Self::GoldIngot,
            267 => Self::IronSword,
            268 => Self::WoodenSword,
            269 => Self::WoodenShovel,
            270 => Self::WoodenPickaxe,
            271 => Self::WoodenAxe,
            272 => Self::StoneSword,
            273 => Self::StoneShovel,
            274 => Self::StonePickaxe,
            275 => Self::StoneAxe,
            276 => Self::DiamondSword,
            277 => Self::DiamondShovel,
            278 => Self::DiamondPickaxe,
            279 => Self::DiamondAxe,
            280 => Self::Stick,
            281 => Self::Bowl,
            282 => Self::MushroomStew,
            283 => Self::GoldSword,
            284 => Self::GoldShovel,
            285 => Self::GoldPickaxe,
            286 => Self::GoldAxe,
            287 => Self::String,
            288 => Self::Feather,
            289 => Self::Gunpowder,
            290 => Self::WoodenHoe,
            291 => Self::StoneHoe,
            292 => Self::IronHoe,
            293 => Self::DiamondHoe,
            294 => Self::GoldHoe,
            295 => Self::Seeds,
            296 => Self::Wheat,
            297 => Self::Bread,
            298 => Self::LeatherHelmet,
            299 => Self::LeatherChestplate,
            300 => Self::LeatherLeggings,
            301 => Self::LeatherBoots,
            302 => Self::ChainmailHelmet,
            303 => Self::ChainmailChestplate,
            304 => Self::ChainmailLeggings,
            305 => Self::ChainmailBoots,
            306 => Self::IronHelmet,
            307 => Self::IronChestplate,
            308 => Self::IronLeggings,
            309 => Self::IronBoots,
            310 => Self::DiamondHelmet,
            311 => Self::DiamondChestplate,
            312 => Self::DiamondLeggings,
            313 => Self::DiamondBoots,
            314 => Self::GoldHelmet,
            315 => Self::GoldChestplate,
            316 => Self::GoldLeggings,
            317 => Self::GoldBoots,
            318 => Self::Flint,
            319 => Self::RawPorkchop,
            320 => Self::CookedPorkchop,
            321 => Self::Painting,
            322 => Self::GoldenApple,
            323 => Self::Sign,
            324 => Self::WoodenDoor,
            325 => Self::Bucket,
            326 => Self::WaterBucket,
            327 => Self::LavaBucket,
            328 => Self::Minecart,
            329 => Self::Saddle,
            330 => Self::IronDoor,
            331 => Self::Redstone,
            332 => Self::Snowball,
            333 => Self::Boat,
            334 => Self::Leather,
            335 => Self::MilkBucket,
            336 => Self::Brick,
            337 => Self::ClayBall,
            338 => Self::SugarCane,
            339 => Self::Paper,
            340 => Self::Book,
            341 => Self::Slimeball,
            342 => Self::ChestMinecart,
            343 => Self::FurnaceMinecart,
            344 => Self::Egg,
            345 => Self::Compass,
            346 => Self::FishingRod,
            347 => Self::Clock,
            348 => Self::GlowstoneDust,
            349 => Self::RawFish,
            350 => Self::CookedFish,
            351 => Self::Dye,
            352 => Self::Bone,
            353 => Self::Sugar,
            354 => Self::Cake,
            355 => Self::Bed,
            356 => Self::Repeater,
            357 => Self::Cookie,
            358 => Self::Map,
            359 => Self::Shears,
            2256 => Self::Record13,
            2257 => Self::RecordCat,
            _ => return None,
        })
    }

    pub const fn definition(self) -> Option<ItemDefinition> {
        match self {
            Self::Block(block) => {
                let raw = block.as_u8();
                if raw == 0 || raw > 96 {
                    None
                } else {
                    Some(ItemDefinition {
                        id: self,
                        name: block.name(),
                        max_stack_size: 64,
                        data: block.item_data(),
                        block: Some(block),
                    })
                }
            }
            Self::IronShovel => Some(standalone(
                self,
                "iron_shovel",
                1,
                ItemData::Durability(250),
            )),
            Self::IronPickaxe => Some(standalone(
                self,
                "iron_pickaxe",
                1,
                ItemData::Durability(250),
            )),
            Self::IronAxe => Some(standalone(self, "iron_axe", 1, ItemData::Durability(250))),
            Self::FlintAndSteel => Some(standalone(
                self,
                "flint_and_steel",
                1,
                ItemData::Durability(64),
            )),
            Self::Apple => Some(standalone(self, "apple", 1, ItemData::None)),
            Self::Bow => Some(standalone(self, "bow", 1, ItemData::None)),
            Self::Arrow => Some(standalone(self, "arrow", 64, ItemData::None)),
            Self::Coal => Some(standalone(self, "coal", 64, ItemData::Subtype(1))),
            Self::Diamond => Some(standalone(self, "diamond", 64, ItemData::None)),
            Self::IronIngot => Some(standalone(self, "iron_ingot", 64, ItemData::None)),
            Self::GoldIngot => Some(standalone(self, "gold_ingot", 64, ItemData::None)),
            Self::IronSword => Some(standalone(self, "iron_sword", 1, ItemData::Durability(250))),
            Self::WoodenSword => Some(standalone(
                self,
                "wooden_sword",
                1,
                ItemData::Durability(59),
            )),
            Self::WoodenShovel => Some(standalone(
                self,
                "wooden_shovel",
                1,
                ItemData::Durability(59),
            )),
            Self::WoodenPickaxe => Some(standalone(
                self,
                "wooden_pickaxe",
                1,
                ItemData::Durability(59),
            )),
            Self::WoodenAxe => Some(standalone(self, "wooden_axe", 1, ItemData::Durability(59))),
            Self::StoneSword => Some(standalone(
                self,
                "stone_sword",
                1,
                ItemData::Durability(131),
            )),
            Self::StoneShovel => Some(standalone(
                self,
                "stone_shovel",
                1,
                ItemData::Durability(131),
            )),
            Self::StonePickaxe => Some(standalone(
                self,
                "stone_pickaxe",
                1,
                ItemData::Durability(131),
            )),
            Self::StoneAxe => Some(standalone(self, "stone_axe", 1, ItemData::Durability(131))),
            Self::DiamondSword => Some(standalone(
                self,
                "diamond_sword",
                1,
                ItemData::Durability(1561),
            )),
            Self::DiamondShovel => Some(standalone(
                self,
                "diamond_shovel",
                1,
                ItemData::Durability(1561),
            )),
            Self::DiamondPickaxe => Some(standalone(
                self,
                "diamond_pickaxe",
                1,
                ItemData::Durability(1561),
            )),
            Self::DiamondAxe => Some(standalone(
                self,
                "diamond_axe",
                1,
                ItemData::Durability(1561),
            )),
            Self::Stick => Some(standalone(self, "stick", 64, ItemData::None)),
            Self::Bowl => Some(standalone(self, "bowl", 64, ItemData::None)),
            Self::MushroomStew => Some(standalone(self, "mushroom_stew", 1, ItemData::None)),
            Self::GoldSword => Some(standalone(self, "gold_sword", 1, ItemData::Durability(32))),
            Self::GoldShovel => Some(standalone(self, "gold_shovel", 1, ItemData::Durability(32))),
            Self::GoldPickaxe => Some(standalone(
                self,
                "gold_pickaxe",
                1,
                ItemData::Durability(32),
            )),
            Self::GoldAxe => Some(standalone(self, "gold_axe", 1, ItemData::Durability(32))),
            Self::String => Some(standalone(self, "string", 64, ItemData::None)),
            Self::Feather => Some(standalone(self, "feather", 64, ItemData::None)),
            Self::Gunpowder => Some(standalone(self, "gunpowder", 64, ItemData::None)),
            Self::WoodenHoe => Some(standalone(self, "wooden_hoe", 1, ItemData::Durability(59))),
            Self::StoneHoe => Some(standalone(self, "stone_hoe", 1, ItemData::Durability(131))),
            Self::IronHoe => Some(standalone(self, "iron_hoe", 1, ItemData::Durability(250))),
            Self::DiamondHoe => Some(standalone(
                self,
                "diamond_hoe",
                1,
                ItemData::Durability(1561),
            )),
            Self::GoldHoe => Some(standalone(self, "gold_hoe", 1, ItemData::Durability(32))),
            Self::Seeds => Some(standalone(self, "seeds", 64, ItemData::None)),
            Self::Wheat => Some(standalone(self, "wheat", 64, ItemData::None)),
            Self::Bread => Some(standalone(self, "bread", 1, ItemData::None)),
            Self::LeatherHelmet => Some(standalone(
                self,
                "leather_helmet",
                1,
                ItemData::Durability(33),
            )),
            Self::LeatherChestplate => Some(standalone(
                self,
                "leather_chestplate",
                1,
                ItemData::Durability(48),
            )),
            Self::LeatherLeggings => Some(standalone(
                self,
                "leather_leggings",
                1,
                ItemData::Durability(45),
            )),
            Self::LeatherBoots => Some(standalone(
                self,
                "leather_boots",
                1,
                ItemData::Durability(39),
            )),
            Self::ChainmailHelmet => Some(standalone(
                self,
                "chainmail_helmet",
                1,
                ItemData::Durability(66),
            )),
            Self::ChainmailChestplate => Some(standalone(
                self,
                "chainmail_chestplate",
                1,
                ItemData::Durability(96),
            )),
            Self::ChainmailLeggings => Some(standalone(
                self,
                "chainmail_leggings",
                1,
                ItemData::Durability(90),
            )),
            Self::ChainmailBoots => Some(standalone(
                self,
                "chainmail_boots",
                1,
                ItemData::Durability(78),
            )),
            Self::IronHelmet => Some(standalone(
                self,
                "iron_helmet",
                1,
                ItemData::Durability(132),
            )),
            Self::IronChestplate => Some(standalone(
                self,
                "iron_chestplate",
                1,
                ItemData::Durability(192),
            )),
            Self::IronLeggings => Some(standalone(
                self,
                "iron_leggings",
                1,
                ItemData::Durability(180),
            )),
            Self::IronBoots => Some(standalone(self, "iron_boots", 1, ItemData::Durability(156))),
            Self::DiamondHelmet => Some(standalone(
                self,
                "diamond_helmet",
                1,
                ItemData::Durability(264),
            )),
            Self::DiamondChestplate => Some(standalone(
                self,
                "diamond_chestplate",
                1,
                ItemData::Durability(384),
            )),
            Self::DiamondLeggings => Some(standalone(
                self,
                "diamond_leggings",
                1,
                ItemData::Durability(360),
            )),
            Self::DiamondBoots => Some(standalone(
                self,
                "diamond_boots",
                1,
                ItemData::Durability(312),
            )),
            Self::GoldHelmet => Some(standalone(self, "gold_helmet", 1, ItemData::Durability(66))),
            Self::GoldChestplate => Some(standalone(
                self,
                "gold_chestplate",
                1,
                ItemData::Durability(96),
            )),
            Self::GoldLeggings => Some(standalone(
                self,
                "gold_leggings",
                1,
                ItemData::Durability(90),
            )),
            Self::GoldBoots => Some(standalone(self, "gold_boots", 1, ItemData::Durability(78))),
            Self::Flint => Some(standalone(self, "flint", 64, ItemData::None)),
            Self::RawPorkchop => Some(standalone(self, "raw_porkchop", 1, ItemData::None)),
            Self::CookedPorkchop => Some(standalone(self, "cooked_porkchop", 1, ItemData::None)),
            Self::Painting => Some(standalone(self, "painting", 64, ItemData::None)),
            Self::GoldenApple => Some(standalone(self, "golden_apple", 1, ItemData::None)),
            Self::Sign => Some(standalone(self, "sign", 1, ItemData::None)),
            Self::WoodenDoor => Some(standalone(self, "wooden_door", 1, ItemData::None)),
            Self::Bucket => Some(standalone(self, "bucket", 1, ItemData::None)),
            Self::WaterBucket => Some(standalone(self, "water_bucket", 1, ItemData::None)),
            Self::LavaBucket => Some(standalone(self, "lava_bucket", 1, ItemData::None)),
            Self::Minecart => Some(standalone(self, "minecart", 1, ItemData::None)),
            Self::Saddle => Some(standalone(self, "saddle", 1, ItemData::None)),
            Self::IronDoor => Some(standalone(self, "iron_door", 1, ItemData::None)),
            Self::Redstone => Some(standalone(self, "redstone", 64, ItemData::None)),
            Self::Snowball => Some(standalone(self, "snowball", 16, ItemData::None)),
            Self::Boat => Some(standalone(self, "boat", 1, ItemData::None)),
            Self::Leather => Some(standalone(self, "leather", 64, ItemData::None)),
            Self::MilkBucket => Some(standalone(self, "milk_bucket", 1, ItemData::None)),
            Self::Brick => Some(standalone(self, "brick", 64, ItemData::None)),
            Self::ClayBall => Some(standalone(self, "clay_ball", 64, ItemData::None)),
            Self::SugarCane => Some(standalone(self, "sugar_cane", 64, ItemData::None)),
            Self::Paper => Some(standalone(self, "paper", 64, ItemData::None)),
            Self::Book => Some(standalone(self, "book", 64, ItemData::None)),
            Self::Slimeball => Some(standalone(self, "slimeball", 64, ItemData::None)),
            Self::ChestMinecart => Some(standalone(self, "chest_minecart", 1, ItemData::None)),
            Self::FurnaceMinecart => Some(standalone(self, "furnace_minecart", 1, ItemData::None)),
            Self::Egg => Some(standalone(self, "egg", 16, ItemData::None)),
            Self::Compass => Some(standalone(self, "compass", 64, ItemData::None)),
            Self::FishingRod => Some(standalone(self, "fishing_rod", 1, ItemData::Durability(64))),
            Self::Clock => Some(standalone(self, "clock", 64, ItemData::None)),
            Self::GlowstoneDust => Some(standalone(self, "glowstone_dust", 64, ItemData::None)),
            Self::RawFish => Some(standalone(self, "raw_fish", 1, ItemData::None)),
            Self::CookedFish => Some(standalone(self, "cooked_fish", 1, ItemData::None)),
            Self::Dye => Some(standalone(self, "dye", 64, ItemData::Subtype(15))),
            Self::Bone => Some(standalone(self, "bone", 64, ItemData::None)),
            Self::Sugar => Some(standalone(self, "sugar", 64, ItemData::None)),
            Self::Cake => Some(standalone(self, "cake", 1, ItemData::None)),
            Self::Bed => Some(standalone(self, "bed", 1, ItemData::None)),
            Self::Repeater => Some(standalone(self, "repeater", 64, ItemData::None)),
            Self::Cookie => Some(standalone(self, "cookie", 8, ItemData::None)),
            Self::Map => Some(standalone(self, "map", 1, ItemData::Map)),
            Self::Shears => Some(standalone(self, "shears", 1, ItemData::Durability(238))),
            Self::Record13 => Some(standalone(self, "record13", 1, ItemData::None)),
            Self::RecordCat => Some(standalone(self, "record_cat", 1, ItemData::None)),
        }
    }
}

/// Raw id ranges that contain an item: block items, the main item list, and records.
const RAW_RANGES: [(u16, u16); 3] = [(1, 96), (256, 359), (2256, 2257)];

/// Stateless immutable registry; lookups allocate nothing.
pub struct ItemRegistry;

impl ItemRegistry {
    pub fn get(raw: u16) -> Option<ItemDefinition> {
        ItemId::from_u16(raw).and_then(ItemId::definition)
    }

    pub fn iter() -> impl Iterator<Item = ItemDefinition> {
        RAW_RANGES
            .into_iter()
            .flat_map(|(start, end)| start..=end)
            .filter_map(ItemRegistry::get)
    }
}
