#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BlockId {
    Air = 0,
    Stone = 1,
    Grass = 2,
    Dirt = 3,
    Cobblestone = 4,
    WoodenPlanks = 5,
    Bedrock = 7,
    Sand = 12,
    Gravel = 13,
    GoldOre = 14,
    IronOre = 15,
    CoalOre = 16,
    Wood = 17,
    Sponge = 19,
    LapisOre = 21,
    LapisBlock = 22,
    Dispenser = 23,
    Sandstone = 24,
    NoteBlock = 25,
    Wool = 35,
    GoldBlock = 41,
    IronBlock = 42,
    DoubleStoneSlab = 43,
    Bricks = 45,
    Tnt = 46,
    Bookshelf = 47,
    MossyCobblestone = 48,
    Obsidian = 49,
    DiamondOre = 56,
    DiamondBlock = 57,
    CraftingTable = 58,
    Furnace = 61,
    LitFurnace = 62,
    RedstoneOre = 73,
    LitRedstoneOre = 74,
    Snow = 80,
    Clay = 82,
    Jukebox = 84,
    Pumpkin = 86,
    Netherrack = 87,
    Glowstone = 89,
    JackOLantern = 91,
}
