#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BlockId {
    Air = 0,
    Stone = 1,
    Grass = 2,
    Dirt = 3,
    Cobblestone = 4,
    WoodenPlanks = 5,
    Bedrock = 7,
    Water = 9,
    Sand = 12,
    Gravel = 13,
    GoldOre = 14,
    IronOre = 15,
    CoalOre = 16,
    Wood = 17,
    Leaves = 18,
    Sponge = 19,
    LapisOre = 21,
    LapisBlock = 22,
    Dispenser = 23,
    Sandstone = 24,
    NoteBlock = 25,
    Wool = 35,
    GoldBlock = 41,
    IronBlock = 42,
    DoubleStoneSlab = 43,
    Bricks = 45,
    Tnt = 46,
    Bookshelf = 47,
    MossyCobblestone = 48,
    Obsidian = 49,
    Torch = 50,
    DiamondOre = 56,
    DiamondBlock = 57,
    CraftingTable = 58,
    Furnace = 61,
    LitFurnace = 62,
    RedstoneOre = 73,
    LitRedstoneOre = 74,
    Ice = 79,
    Snow = 80,
    Clay = 82,
    Jukebox = 84,
    Pumpkin = 86,
    Netherrack = 87,
    Glowstone = 89,
    JackOLantern = 91,
    // Beta stores wood and leaf species in block metadata. The chunk stores a
    // single compact value per block, so each species gets its own variant.
    SpruceLeaves = 200,
    BirchLeaves = 201,
    SpruceWood = 202,
    BirchWood = 203,
    // Wall attachment is encoded in the compact block value until chunk
    // metadata is introduced. These values are private to our save format.
    TorchWest = 204,
    TorchEast = 205,
    TorchNorth = 206,
    TorchSouth = 207,
}

impl BlockId {
    /// Native chunk/save ID. Private variants overlap Beta IDs; use
    /// `beta_state()` for the Beta identity and metadata instead.
    pub const fn as_u8(self) -> u8 {
        self as u8
    }

    pub const fn from_u8(value: u8) -> Option<Self> {
        Some(match value {
            0 => Self::Air,
            1 => Self::Stone,
            2 => Self::Grass,
            3 => Self::Dirt,
            4 => Self::Cobblestone,
            5 => Self::WoodenPlanks,
            7 => Self::Bedrock,
            9 => Self::Water,
            12 => Self::Sand,
            13 => Self::Gravel,
            14 => Self::GoldOre,
            15 => Self::IronOre,
            16 => Self::CoalOre,
            17 => Self::Wood,
            18 => Self::Leaves,
            19 => Self::Sponge,
            21 => Self::LapisOre,
            22 => Self::LapisBlock,
            23 => Self::Dispenser,
            24 => Self::Sandstone,
            25 => Self::NoteBlock,
            35 => Self::Wool,
            41 => Self::GoldBlock,
            42 => Self::IronBlock,
            43 => Self::DoubleStoneSlab,
            45 => Self::Bricks,
            46 => Self::Tnt,
            47 => Self::Bookshelf,
            48 => Self::MossyCobblestone,
            49 => Self::Obsidian,
            50 => Self::Torch,
            56 => Self::DiamondOre,
            57 => Self::DiamondBlock,
            58 => Self::CraftingTable,
            61 => Self::Furnace,
            62 => Self::LitFurnace,
            73 => Self::RedstoneOre,
            74 => Self::LitRedstoneOre,
            79 => Self::Ice,
            80 => Self::Snow,
            82 => Self::Clay,
            84 => Self::Jukebox,
            86 => Self::Pumpkin,
            87 => Self::Netherrack,
            89 => Self::Glowstone,
            91 => Self::JackOLantern,
            200 => Self::SpruceLeaves,
            201 => Self::BirchLeaves,
            202 => Self::SpruceWood,
            203 => Self::BirchWood,
            204 => Self::TorchWest,
            205 => Self::TorchEast,
            206 => Self::TorchNorth,
            207 => Self::TorchSouth,
            _ => return None,
        })
    }
}
